import { Language } from './types';

export const TRANSLATIONS = {
  zh: {
    title: "維港專業僱傭中心",
    subTitle: "《僱主資料表格》",
    intro: "1️⃣ 以下全部資料均會填在僱傭合約和入境處表格之內\n2️⃣ 如果某些問題不肯定，可以留空及後補\n3️⃣ 中文或英文填寫也可以，英文為佳\n4️⃣ 填寫完成後，在最底按「預覽」的藍色按鈕",
    clear: "清除資料",
    clearConfirm: "確定要清除所有資料嗎？此動作無法復原。",
    navZh: "中文",
    navEn: "English",
    preview: "預覽",
    back: "返回修改",
    previewTitle: "預覽頁，請檢查以下資料後，在最底按「匯出文字和 WhatsApp 本公司」的綠色按鈕",
    exportBtn: "透過 WhatsApp 匯出以上文字及傳送給本公司",
    exportTip: "(資料過長，請分開點擊發送)",
    whatsappPrefix: "*僱主資料表格*\n\n",
    empty: "未填寫",
    labels: {
      employerName: "僱主全名",
      address: "合約地址 (即新外傭工作及居住地址)",
      housingType: "住宅類別",
      houseSize: "住宅面積 (平方呎)",
      bedrooms: "睡房數量 (睡房 + 工人房)",
      nationality: "僱主國籍",
      occupation: "僱主職業",
      income: "僱主平均每月入息",
      roomArrangement: "獨立工人房 (一人房間)",
      roomSize: "工人房面積",
      roomShareChild: "與哪位小孩？(例如：3歲女兒)",
      roomOther: "請填寫其他住宿安排",
      salaryType: "新外傭每月薪金",
      salaryOtherAmount: "請填寫其他薪金",
      foodAllowance: "新外傭每月膳食津貼",
      foodAllowanceAmount: "請填寫其他膳津金額",
      appType: "新外傭申請類別",
      localWorkArrangement: "新外傭上班的安排",
      localVacationDays: "回去多少天？",
      overseasWorkArrangement: "新外傭上班的安排",
      overseasArrivalMonth: "甚麼月份飛香港",
      familyCount: "除了僱主，還有多少位家庭成員（只計算住在合約地址的成員）",
      expectingBaby: "有準備出世的嬰兒嗎?",
      babyDueDateMonth: "何時預產期？",
      babyGender: "嬰兒性別",
      hasOtherHelpers: "以上任何家庭成員，現時有僱用其他外傭 或 未來3個月 會聘用其他新外傭嗎？（包括以上成員的其他住所的外傭 和 已經入紙申請的新外傭）",
      oldHelperCount: "多少位舊外傭？",
      carWash: "要洗車?",
      hasDogs: "有狗?",
      dogCount: "多少狗？",
      hasCats: "有貓?",
      catCount: "多少貓？",
      hasOtherPets: "有其他寵物?",
      otherPetDetails: "什麼寵物和數量？",
      remarks: "新外傭的其他工作",
      // Family Sub-labels
      familyMemberTitle: "第 {i} 位成員",
      fullName: "全名",
      yob: "出生年份",
      relation: "與僱主關係",
      relationOther: "請填寫關係",
      hkid: "香港身份證號碼",
      // Helper Sub-labels
      helperTitle: "第 {i} 位舊外傭",
      helperName: "舊外傭全名",
      helperHkid: "舊外傭身份證號碼",
      contractNo: "舊合約編號",
      visaExpiry: "簽證獲批准在港逗留期限 (即合約何時完結)",
      helperEmployer: "哪位家庭成員聘用",
      arrangement: "此舊外傭的安排",
      handoverDays: "交接期多少日？",
    },
    shortLabels: {
      employerName: "僱主",
      address: "地址",
      housingType: "住宅",
      houseSize: "面積",
      bedrooms: "睡房",
      nationality: "國籍",
      occupation: "職業",
      income: "入息",
      roomArrangement: "工人房",
      roomSize: "房面積",
      roomShareChild: "同房小孩",
      roomOther: "其他住宿",
      salaryType: "薪金",
      salaryOtherAmount: "工資",
      foodAllowance: "膳津",
      foodAllowanceAmount: "金額",
      appType: "類別",
      localWorkArrangement: "上班安排",
      localVacationDays: "回鄉天數",
      overseasWorkArrangement: "上班安排",
      overseasArrivalMonth: "月份",
      familyCount: "家庭人數",
      expectingBaby: "準備出世嬰兒",
      babyDueDateMonth: "預產期",
      babyGender: "性別",
      hasOtherHelpers: "其他外傭",
      oldHelperCount: "舊外傭數",
      carWash: "洗車",
      hasDogs: "養狗",
      dogCount: "數量",
      hasCats: "養貓",
      catCount: "數量",
      hasOtherPets: "其他寵物",
      otherPetDetails: "詳情",
      remarks: "其他工作",
      familyMemberTitle: "成員 {i}",
      fullName: "全名",
      yob: "年份",
      relation: "關係",
      relationOther: "其他",
      hkid: "HKID",
      helperTitle: "舊外傭 {i}",
      helperName: "全名",
      helperHkid: "HKID",
      contractNo: "合約號碼",
      visaExpiry: "合約完結",
      helperEmployer: "誰是僱主",
      arrangement: "安排",
      handoverDays: "交接日",
    },
    options: {
      pleaseSelect: "請選擇",
      yes: "有",
      no: "沒有",
      housing: ["單層單位", "獨立屋"],
      rooms: ["1房", "2房", "3房", "4房", "5房", "6房", "7房", "8房", "9房", "10房", "11房", "12房"],
      roomArrangement: [
        "有工人房", "與小孩同房", "與長者同房", "與女僱主同房", "與另一外傭同房", "其他"
      ],
      salary: ["最低工資", "其他"],
      food: ["沒有膳津，一起吃", "有膳食津貼"],
      appType: ["香港完約、特別個案或續約", "海外外傭"],
      localWork: ["先上班，後回鄉", "先回鄉，後上班"],
      overseasWork: ["盡快四個月內", "安排在某月份飛香港"],
      months: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
      genders: ["男孩", "女孩", "孖仔", "孖女", "龍鳳胎"],
      helperArrangement: [
        "此舊外傭是續約",
        "繼續留用此舊外傭 (即增聘新外傭)",
        "此舊外傭先走，新外傭才入",
        "此舊外傭走，但想有交接期"
      ],
      relations: ["父親","母親","夫婦","兒子","女兒","哥哥","弟弟","姊姊","妹妹","外父","外母","兒媳","女婿","其他"],
      planningToHire: "現在無但準備聘請"
    }
  },
  en: {
    title: "Horizon Employment Agency",
    subTitle: "《Employer Information Form》",
    intro: "1️⃣ All information below will be filled into the employment contract and Immigration Department forms.\n2️⃣ If unsure, leave a blank and provide later.\n3️⃣ After completing the form, click the blue button “Preview” at the bottom.",
    clear: "Clear",
    clearConfirm: "Are you sure you want to clear all data? This action cannot be undone.",
    navZh: "中文",
    navEn: "English",
    preview: "Preview",
    back: "Back to Edit",
    previewTitle: "Preview page, please check the information below, then click the green button “Export Text And WhatsApp to Our Company” at the bottom",
    exportBtn: "Export Above Text via WhatsApp and Send to Our Company",
    exportTip: "(Data too long, please send in parts)",
    whatsappPrefix: "*Employer Information Form*\n\n",
    empty: "Empty",
    labels: {
      employerName: "Employer Full Name",
      address: "Contract Address (i.e. New Helper’s Work and Residence Address)",
      housingType: "Housing Type",
      houseSize: "House Size, Area (Sq. Ft.)",
      bedrooms: "Number of Bedrooms (Including Maid's Room)",
      nationality: "Employer Nationality",
      occupation: "Employer Occupation",
      income: "Employer Average Monthly Income",
      roomArrangement: "Maid Room (Single Room)",
      roomSize: "Room Size",
      roomShareChild: "Which Kid? (e.g. 3 Years Old Daughter)",
      roomOther: "Please Specify Other Sleeping Arrangement",
      salaryType: "New Helper Monthly Salary",
      salaryOtherAmount: "Please Enter Other Salary",
      foodAllowance: "New Helper Monthly Food Allowance",
      foodAllowanceAmount: "Please Enter Allowance Amount",
      appType: "New Helper Application Type",
      localWorkArrangement: "Onboarding Arrangement",
      localVacationDays: "How Many Days For Home Vacation",
      overseasWorkArrangement: "Onboarding Arrangement",
      overseasArrivalMonth: "Which Month Arrive in HK",
      familyCount: "Besides the Employer, How Many Other Family Members Live at the Contract Address?",
      expectingBaby: "Expecting Newborn Baby?",
      babyDueDateMonth: "Estimated Date of Delivery",
      babyGender: "Baby's Gender",
      hasOtherHelpers: "Do Any of the Aforementioned Family Members Currently Employ Another Helper, or Plan to Hire One in the Next 3 Months? (Including Helpers at Other Residences or Applications Already Submitted)",
      oldHelperCount: "How Many Old Helpers?",
      carWash: "Car Wash?",
      hasDogs: "Dogs?",
      dogCount: "How Many Dogs",
      hasCats: "Cats?",
      catCount: "How Many Cats",
      hasOtherPets: "Other Pets?",
      otherPetDetails: "Pet Type and Quantity?",
      remarks: "Other Duties for New Helper",
      // Family Sub-labels
      familyMemberTitle: "Member {i}",
      fullName: "Full Name",
      yob: "Year of Birth",
      relation: "Relationship With The Employer",
      relationOther: "Please specify relationship",
      hkid: "HKID Number",
      // Helper Sub-labels
      helperTitle: "Old Helper {i}",
      helperName: "Helper Full Name",
      helperHkid: "Helper HKID Number",
      contractNo: "Contract Number",
      visaExpiry: "Visa Expiry (Contract End Date)",
      helperEmployer: "Which Family Member Employed",
      arrangement: "Arrangement For This Helper",
      handoverDays: "How Many Days is the Handover Period",
    },
    shortLabels: {
      employerName: "Employer",
      address: "Address",
      housingType: "Housing",
      houseSize: "Size",
      bedrooms: "Bedrooms",
      nationality: "Nationality",
      occupation: "Occupation",
      income: "Income",
      roomArrangement: "Maid Room",
      roomSize: "Size",
      roomShareChild: "Share w/ Kid",
      roomOther: "Other Room",
      salaryType: "Salary",
      salaryOtherAmount: "Wage",
      foodAllowance: "Food Allowance",
      foodAllowanceAmount: "Amount",
      appType: "Appli. Type",
      localWorkArrangement: "Work Arrange",
      localVacationDays: "Vacation Days",
      overseasWorkArrangement: "Work Arrange",
      overseasArrivalMonth: "Arrive in",
      familyCount: "Family Member",
      expectingBaby: "Expecting Newborn",
      babyDueDateMonth: "Due Date",
      babyGender: "Gender",
      hasOtherHelpers: "Other Helpers",
      oldHelperCount: "Count",
      carWash: "Car Wash",
      hasDogs: "Dogs",
      dogCount: "Count",
      hasCats: "Cats",
      catCount: "Count",
      hasOtherPets: "Other Pets",
      otherPetDetails: "Details",
      remarks: "Duties",
      familyMemberTitle: "Member {i}",
      fullName: "Name",
      yob: "YOB",
      relation: "Relation",
      relationOther: "Other",
      hkid: "HKID",
      helperTitle: "Helper {i}",
      helperName: "Name",
      helperHkid: "HKID",
      contractNo: "Contract No",
      visaExpiry: "Visa Expiry",
      helperEmployer: "Employer",
      arrangement: "Arrangement",
      handoverDays: "Handover Days"
    },
    options: {
      pleaseSelect: "Please Select",
      yes: "Yes",
      no: "No",
      housing: ["Flat", "Detached house"],
      rooms: ["1 room", "2 rooms", "3 rooms", "4 rooms", "5 rooms", "6 rooms", "7 rooms", "8 rooms", "9 rooms", "10 rooms", "11 rooms", "12 rooms"],
      roomArrangement: [
        "Yes, separate room", "Share room with child", "Share room with elderly", "Share room with female employer", "Share room with another helper", "Other"
      ],
      salary: ["Minimum wage", "Other"],
      food: ["No allowance, share food", "With allowance"],
      appType: ["HK finish contract／Special case／Contract renewal", "Overseas helper"],
      localWork: ["Work first, defer home vacation", "Home vacation first, work later"],
      overseasWork: ["ASAP (within 4 months)", "Arrive in specific month"],
      months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
      genders: ["Boy", "Girl", "Boy twins", "Girl twins", "Boy-girl twins"],
      helperArrangement: [
        "This helper is renewing contract",
        "Continue employing this old helper (i.e. hiring an additional new helper)",
        "Old helper leaves, new helper starts",
        "This old helper will be replaced, and a handover period is required"
      ],
      relations: ["Father","Mother","Spouse","Son","Daughter","Brother","Sister","Father-in-law","Mother-in-law","Daughter-in-law","Son-in-law","Other"],
      planningToHire: "Not now but planning to hire"
    }
  }
};

export const getLang = (lang: Language) => TRANSLATIONS[lang];